### ISSUE TITLE
PHP 8.1 deprecation warning

### ISSUE THREAD

**Issue by horst-n** [BitPoet/AdminDevModeColors#1]
I found this with PHP 8.1
```
Deprecated: Function strftime() is deprecated in ... site/modules/AdminDevModeColors/AdminDevModeColors.module on line 53

  53:        $ts = strftime("%Y%m%d%H%M%S", filemtime($path));

```
changing it simple to 
```
  53:        $ts = filemtime($path);
```
or
```
  53:        $ts = 'ts=' . filemtime($path);
```
seems to fix it.

**Comment by BitPoet** [comment]
Thanks for reporting this! I've replaced strftime() with date(), as I prefer a human readable timestamps for cache busting. PHP 8.1 should be happy now (haven't tested it with 8.1 myself yet).

**Comment by horst-n** [comment]
Thanks for fixing so fast. Would have had time until PHP 9s first release. :-)
And yes, date() is a better replacement!
